pgjdbc/r2dbc-postgresql

src/main/java/io/r2dbc/postgresql/PostgresqlRow.java, src/main/java/io/r2dbc/postgresql/PostgresqlRowMetadata.java, src/main/java/io/r2dbc/postgresql/codec/DefaultCodecs.java, src/main/java/io/r2dbc/postgresql/message/backend/DataRow.java, src/test/java/io/r2dbc/postgresql/codec/DefaultCodecsTest.java
Evidence suggests that using the Java 8 Stream API leads to performance decreases and excessive garbage generation.  While this won't matter in most cases, and allowing use of its superior API, high-traffic code should stay away from it.  This change updates the implementation to remove the use of the Stream API in various places where performance and garbage generation will matter significantly.
=> Reduce Stream Usage

src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactory.java, src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java, src/test/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryTest.java, src/test/java/io/r2dbc/postgresql/client/ReactorNettyClientTest.java
ReactorNettyClient now exposes a factory method returning
Mono<ReactorNettyClient> to not block on connect.
New connection requests yield in creating a new connection
and do not use a connection pool.
[resolves #10]
=> Introduce non-blocking ReactorNettyClient connect method

src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryProvider.java, src/test/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryProviderTest.java
`getDriver()` returns the driver identifier postgresql.
[resolves #77]
=> Add ConnectionFactoryProvider.getDriver() implementation

src/main/java/io/r2dbc/postgresql/PostgresqlConnection.java, src/test/java/io/r2dbc/postgresql/PostgresqlConnectionTest.java
This is a fix for ticket #139. It will not compile without the patches from branch stubbed-out-spi, so builds and test will fail prior to merging it.
=> Fixed rollback behavior in case of transaction status OPEN or FAILED

src/main/java/io/r2dbc/postgresql/PostgresqlRow.java, src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java, src/main/java/io/r2dbc/postgresql/message/backend/BackendMessageDecoder.java, src/main/java/io/r2dbc/postgresql/message/backend/BackendMessageEnvelopeDecoder.java, src/main/java/io/r2dbc/postgresql/message/backend/BackendMessageUtils.java, src/main/java/io/r2dbc/postgresql/message/backend/CopyData.java, src/main/java/io/r2dbc/postgresql/message/backend/DataRow.java, src/test/java/io/r2dbc/postgresql/message/backend/BackendMessageDecoderTest.java, src/test/java/io/r2dbc/postgresql/message/backend/BackendMessageEnvelopeDecoderTest.java
CompositeByteBuf::discardReadComponents was called before mapping process in case of delayed mapping. 
Now we create new CompositeByteBuf from required parts for every envelope and that allows us to call discardReadComponents safe.
It should fix issues #107, #91 and #86.
#86 was tested with this [gist](https://gist.github.com/croudet/e34275f758765f7799b4870a45e8163d).
#107 was tested with this [gist](https://gist.github.com/flyaruu/239a950ffda6f3fc544faffffc866f12) and database from issue
#91 wasn't tested (need some help from someone with kotlin environment), but issue seems to be the same.
=> Parallel mapping fix

src/main/java/io/r2dbc/postgresql/message/backend/CommandComplete.java, src/test/java/io/r2dbc/postgresql/message/backend/CommandCompleteTest.java
Select commands on GreenplumDB (possibly older versions of Postgresql as well) do not return the amount of result records in the tag.
Added a lenght check on the tokenized tag to prevent array index out of bounds.
=> Avoid array index out of bounds on missing result size in tag

pom.xml, src/main/java/io/r2dbc/postgresql/PostgresqlConnection.java, src/main/java/io/r2dbc/postgresql/PostgresqlResult.java, src/main/java/io/r2dbc/postgresql/codec/AbstractArrayCodec.java, src/main/java/io/r2dbc/postgresql/codec/AbstractCodec.java, src/main/java/io/r2dbc/postgresql/codec/BigDecimalCodec.java, src/main/java/io/r2dbc/postgresql/codec/BlobCodec.java, src/main/java/io/r2dbc/postgresql/codec/BooleanCodec.java, src/main/java/io/r2dbc/postgresql/codec/DoubleCodec.java, src/main/java/io/r2dbc/postgresql/codec/FloatCodec.java, src/main/java/io/r2dbc/postgresql/codec/InetAddressCodec.java, src/main/java/io/r2dbc/postgresql/codec/InstantCodec.java, src/main/java/io/r2dbc/postgresql/codec/IntegerCodec.java, src/main/java/io/r2dbc/postgresql/codec/LocalDateCodec.java, src/main/java/io/r2dbc/postgresql/codec/LocalDateTimeCodec.java, src/main/java/io/r2dbc/postgresql/codec/LocalTimeCodec.java, src/main/java/io/r2dbc/postgresql/codec/LongCodec.java, src/main/java/io/r2dbc/postgresql/codec/OffsetDateTimeCodec.java, src/main/java/io/r2dbc/postgresql/codec/ShortCodec.java, src/main/java/io/r2dbc/postgresql/codec/StringCodec.java, src/main/java/io/r2dbc/postgresql/codec/UuidCodec.java, src/main/java/io/r2dbc/postgresql/codec/ZonedDateTimeCodec.java, src/test/java/io/r2dbc/postgresql/client/ParameterAssert.java, src/test/java/io/r2dbc/postgresql/client/ReactorNettyClientTest.java, src/test/java/io/r2dbc/postgresql/codec/AbstractCodecTest.java, src/test/java/io/r2dbc/postgresql/codec/CodecIntegrationTest.java
There's still one leak in TestKit.batch method: since nobody subscribes on "SELECT value FROM test" result PostgresqlRow.data just leaks, but I'm not sure is that a leak in a driver or wrong api usage.
Test can be written like this to prevent leak.
```java
@Test
default void batch() {
getJdbcOperations().execute("INSERT INTO test VALUES (100)");
Mono.from(getConnectionFactory().create())
.flatMapMany(connection -> Flux.from(connection
.createBatch()
.add("INSERT INTO test VALUES(200)")
.add("SELECT value FROM test")
.execute())
.concatWith(Mono.from(connection.close()).then(Mono.empty())))
.as(StepVerifier::create)
.consumeNextWith(r -> Mono.from(r.getRowsUpdated()).subscribe())
.consumeNextWith(r -> Flux.from(r.map((row, meta) -> row.get(0))).subscribe())
.verifyComplete();
}
```
=> Memory leak fixes

.gitignore, README.md, src/main/java/io/r2dbc/postgresql/codec/DefaultCodecs.java, src/main/java/io/r2dbc/postgresql/codec/JsonCodec.java, src/main/java/io/r2dbc/postgresql/codec/JsonbCodec.java, src/main/java/io/r2dbc/postgresql/type/PostgresqlObjectId.java, src/test/java/io/r2dbc/postgresql/codec/CodecIntegrationTest.java, src/test/java/io/r2dbc/postgresql/codec/DefaultCodecsTest.java, src/test/java/io/r2dbc/postgresql/codec/JsonCodecTest.java, src/test/java/io/r2dbc/postgresql/codec/JsonbCodecTest.java
Hi @mp911de! I'm opening this PR as an alternative to #39 but using [Jackson](https://github.com/FasterXML/jackson) dependency instead of GSON. I also took into account your suggestions to provide a certain level of flexibility and added return types for `ByteBuf`, `byte[]`, `String` and `InputStream`.
I only added the codec to `JSONB` since we'll need another codec for `JSON`. This is because the `doEncode(Object value)` method does not have any way to choose which one it should encode: JSON or JSONB.
I can open another PR after this one with the `JSON` codec or add it to this PR if you think it would be ok 🙂 
Cheers!
=> Implement JSON and JSONB codecs

src/test/resources/pg_hba.conf
When the test suite is run with the testcontainers backend, the
integration tests were failing with newer versions of the postgres
docker image. The failures were caused by the docker-container not
properly starting which itself was caused by a missing entry in the
`pg_hba.conf` for local connections.
This commit adds the missing configuration for local connections.
=> Add an auth-config for local connections in testing

README.md, src/main/java/io/r2dbc/postgresql/codec/DateCodec.java, src/main/java/io/r2dbc/postgresql/codec/InstantCodec.java, src/main/java/io/r2dbc/postgresql/codec/LocalDateTimeCodec.java, src/test/java/io/r2dbc/postgresql/AbstractCodecIntegrationTests.java, src/test/java/io/r2dbc/postgresql/codec/DateCodecTest.java, src/test/java/io/r2dbc/postgresql/codec/InstantCodecTest.java
Instants were (IMO) incorrectly mapped to `TIMESTAMP` on the wire. The [official postgres java docs](https://jdbc.postgresql.org/documentation/head/8-date-time.html) say so as well.
This PR includes two commits/changes:
a) Make `InstantCodec` use `TIMESTAMPTZ` - this is straightforward, tests have been updated accordingly
b) Make `DateCodec` not use `InstantCodec` anymore and use `LocalDateTime` instead. This is a bit more involved as we have to make use of LocalDateTime handles dates without time properly and we need to do some date-object juggling in general.
I guess this "breaks backwards compatibility" in a way, but as this can be considered a bug (we ran into this by accident as our test-suite just didn't want to turn green), it should still be fixed in my opinion.
If this passes the …
=> Fix instant handling

src/main/java/io/r2dbc/postgresql/codec/AbstractNumericCodec.java, src/test/java/io/r2dbc/postgresql/AbstractCodecIntegrationTests.java
This PR just adds the `OID` data type to the supported numeric types. This allows PostgreSQL's `OID` type to be decoded as `Integer`, `Long`, etc. According to PostgreSQL [documentation ](https://www.postgresql.org/docs/current/datatype-oid.html), the `OID` type is implemented as an unsigned  four-byte integer, so there should be no problem using the `NumericAbstractCodec` on this type 🙂
=> Add OID to the NumericAbstractCodec SUPPORTED_TYPES

src/main/java/io/r2dbc/postgresql/PostgresqlConnectionConfiguration.java, src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryProvider.java
proposal to simplify the ```PostgresqlConnectionFactoryProvider```
=> Simplify factory provider

src/main/java/io/r2dbc/postgresql/DisabledStatementCache.java, src/main/java/io/r2dbc/postgresql/LimitedStatementCache.java, src/main/java/io/r2dbc/postgresql/PostgresqlConnectionConfiguration.java, src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactory.java, src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryProvider.java, src/main/java/io/r2dbc/postgresql/StatementCache.java, src/main/java/io/r2dbc/postgresql/client/Client.java, src/main/java/io/r2dbc/postgresql/client/ExtendedQueryMessageFlow.java, src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java, src/test/java/io/r2dbc/postgresql/DisabledStatementCacheTest.java, src/test/java/io/r2dbc/postgresql/LimitedStatementCacheTest.java, src/test/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryProviderTest.java, src/test/java/io/r2dbc/postgresql/client/ExtendedQueryMessageFlowTest.java, src/test/java/io/r2dbc/postgresql/client/ReactorNettyClientIntegrationTests.java, src/test/java/io/r2dbc/postgresql/client/TestClient.java, src/test/java/io/r2dbc/postgresql/util/PgBouncer.java, src/test/java/io/r2dbc/postgresql/util/PostgresqlServerExtension.java
https://github.com/r2dbc/r2dbc-postgresql/issues/223
Added preparedStatementCacheQueries parameter, which controls cache behaviour.
When cache limit is reached last used statement is closed before parsing new one.
When cache limit is 0 caching of statement is disabled and unnamed statements are used in extended message flow.
Negative values stand for IndefiniteStatementCache (default one).
=> Prepared statement cache configuration

src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java, src/test/java/io/r2dbc/postgresql/client/ReactorNettyClientIntegrationTests.java
If we send requests fast enough client can mix frames of different queries. That leads to "Unknown portal" error (when one flow send `Sync` between others `Bind` and `Execute`) or "Source emitted more than one item" (when one flow send `Sync` between others `Execute` and `Sync` - its result will receive `CommandComplete` from both queries).
It can easely be fixed by changing concurrent subscribing to request `Publisher`s to concatmapping them.
Should fix #207
=> Fix for concurrent exchanging on one client

README.md, src/main/java/io/r2dbc/postgresql/ConnectionContext.java, src/main/java/io/r2dbc/postgresql/ExtendedQueryPostgresqlStatement.java, src/main/java/io/r2dbc/postgresql/PostgresqlBatch.java, src/main/java/io/r2dbc/postgresql/PostgresqlConnection.java, src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactory.java, src/main/java/io/r2dbc/postgresql/PostgresqlResult.java, src/main/java/io/r2dbc/postgresql/PostgresqlRow.java, src/main/java/io/r2dbc/postgresql/SimpleQueryPostgresqlStatement.java, src/main/java/io/r2dbc/postgresql/api/RefCursor.java, src/main/java/io/r2dbc/postgresql/codec/DefaultCodecs.java, src/main/java/io/r2dbc/postgresql/codec/RefCursorCodec.java, src/main/java/io/r2dbc/postgresql/codec/RefCursorNameCodec.java, src/test/java/io/r2dbc/postgresql/AbstractIntegrationTests.java, src/test/java/io/r2dbc/postgresql/ExtendedQueryPostgresqlStatementTest.java, src/test/java/io/r2dbc/postgresql/MockContext.java, src/test/java/io/r2dbc/postgresql/PostgresqlBatchTest.java, src/test/java/io/r2dbc/postgresql/PostgresqlResultTest.java, src/test/java/io/r2dbc/postgresql/PostgresqlRowTest.java, src/test/java/io/r2dbc/postgresql/SimpleQueryPostgresqlStatementTest.java, src/test/java/io/r2dbc/postgresql/codec/RefCursorCodecTest.java, src/test/java/io/r2dbc/postgresql/feature/RefCursorIntegrationTests.java
We now can decode a `RefCursor` from a `Row` and fetch the data that the cursor holds.
```java
RefCursor cursor = row.get("my_store_procedure", RefCursor.class);
// later
cursor.fetch().then(cursor.close());
```
[closes #173]
/cc @Squiry @davecramer
=> Add support for RefCursor

src/main/java/io/r2dbc/postgresql/ExtendedQueryPostgresqlStatement.java, src/main/java/io/r2dbc/postgresql/PostgresqlConnection.java, src/main/java/io/r2dbc/postgresql/PostgresqlResult.java, src/main/java/io/r2dbc/postgresql/SimpleQueryPostgresqlStatement.java, src/main/java/io/r2dbc/postgresql/client/ExtendedQueryMessageFlow.java, src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java, src/main/java/io/r2dbc/postgresql/util/FluxDiscardOnCancel.java, src/main/java/io/r2dbc/postgresql/util/Operators.java, src/test/java/io/r2dbc/postgresql/PostgresCancelIntegrationTests.java, src/test/java/io/r2dbc/postgresql/util/FluxDiscardOnCancelUnitTests.java
FluxDiscardOnCancel replays source signals unless cancelling
the subscription. On cancellation, the subscriber requests Long.MAX_VALUE
to drain the source and discard elements that are emitted afterwards.
[closes #222]
/cc @squiry
=> Add DiscardOnCancel operator

src/main/java/io/r2dbc/postgresql/PostgresqlConnection.java, src/main/java/io/r2dbc/postgresql/api/PostgresqlConnection.java, src/main/java/io/r2dbc/postgresql/client/Client.java, src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java, src/test/java/io/r2dbc/postgresql/PostgresNotificationIntegrationTests.java, src/test/java/io/r2dbc/postgresql/client/TestClient.java, src/test/java/io/r2dbc/postgresql/util/ConnectionIntrospector.java
We now terminate the notification stream (PostgresqlConnection.getNotifications()) when the connection gets disconnected. If the connection is closed normally, the stream terminates successfully (onComplete). Unintended disconnects result in an error (onError).
Requires forward-port to `master` and `0.8.x.`.
[#212]
=> Terminate Notification stream on disconnect

README.md, src/main/java/io/r2dbc/postgresql/codec/BigIntegerCodec.java, src/main/java/io/r2dbc/postgresql/codec/DefaultCodecs.java, src/test/java/io/r2dbc/postgresql/AbstractCodecIntegrationTests.java, src/test/java/io/r2dbc/postgresql/codec/BigIntegerCodecTest.java
Applicable to any numeric type with scale 0
[resolves #233]
=> Add codec for BigInteger

src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryProvider.java, src/test/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryProviderTest.java
added workaround for cases when "options" have been provided via URL and are represented with a String, not a Map)
Make sure that:
Resolves #271
=> adds capability to specify connections options via URL

README.md, src/main/java/io/r2dbc/postgresql/PostgresqlConnectionConfiguration.java, src/main/java/io/r2dbc/postgresql/codec/EnumCodec.java, src/main/java/io/r2dbc/postgresql/codec/PostgresTypes.java, src/test/java/io/r2dbc/postgresql/AbstractCodecIntegrationTests.java, src/test/java/io/r2dbc/postgresql/CodecBinaryFormatIntegrationTests.java, src/test/java/io/r2dbc/postgresql/codec/EnumCodecIntegrationTests.java, src/test/java/io/r2dbc/postgresql/codec/EnumCodecUnitTests.java
We now provide a `EnumCodec` to map Java types to Postgres enumerated types.
[closes #244]
=> Add support for Postgres enumerated types

src/main/java/io/r2dbc/postgresql/codec/DefaultCodecs.java, src/main/java/io/r2dbc/postgresql/codec/Point.java, src/main/java/io/r2dbc/postgresql/codec/PointCodec.java, src/test/java/io/r2dbc/postgresql/AbstractCodecIntegrationTests.java, src/test/java/io/r2dbc/postgresql/codec/PointCodecTest.java
Make sure that:
related to issue previously opened support for geometric types - #282
=> Add support for point type

src/main/java/io/r2dbc/postgresql/codec/AbstractNumericCodec.java, src/main/java/io/r2dbc/postgresql/codec/AbstractTemporalCodec.java, src/main/java/io/r2dbc/postgresql/type/PostgresqlObjectId.java, src/test/java/io/r2dbc/postgresql/codec/InstantCodecUnitTests.java, src/test/java/io/r2dbc/postgresql/codec/IntegerCodecUnitTests.java
closes #301
Make sure that:
#301
=> #301 Fix IllegalArgumentException issue in TemporalCodec.canDecode on custom type object

src/main/java/io/r2dbc/postgresql/codec/PostgresqlDateTimeFormatter.java, src/test/java/io/r2dbc/postgresql/codec/InstantCodecUnitTests.java, src/test/java/io/r2dbc/postgresql/codec/LocalDateTimeCodecUnitTests.java, src/test/java/io/r2dbc/postgresql/codec/OffsetDateTimeCodecUnitTests.java, src/test/java/io/r2dbc/postgresql/codec/ZonedDateTimeCodecUnitTests.java
Make sure that:
Previously, the timestamp parser would throw an exception if it received
a value with an offset of "+00:00". It would only work if the offset
were "+00". Now, it works with both formats.
Fixes #320
There are no new APIs.
I encountered this issue when using this driver to connect to CockroachDB.
=> Parse UTC timestamps with +00:00 offset

src/main/java/io/r2dbc/postgresql/client/BalancedResolverGroup.java, src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java
As an alternative to #120 this solution will allow the client to connect to a postgres master/slave setup through multiple pgbouncers.
This is impossible to unit test properly, but I can provide credentials to manually test the behavior of the resolver.
This change should be backwards compatible, so I didn't make the resolving behavior configurable.
Should this feature be merged to main or also to the 0.8.x branch?
=> Use RoundRobinInetAddressResolver for DNS resolution

.github/workflows/ci.yml, .github/workflows/release.yml
I just updated my fork of r2dbc-postgresql, and I got failure emails from GitHub Actions triggered on my fork due to unavailable credentials for the Sonatype repository. This change will restrict those actions to only run on the main repository (pgjdbc/r2dbc-postgresql).
=> Restrict CI and release task to pgjdbc/r2dbc-postgresql repo

src/main/java/io/r2dbc/postgresql/util/GeneratedValuesUtils.java, src/test/java/io/r2dbc/postgresql/util/GeneratedValuesUtilsUnitTests.java
=> [#377] Fix regular expression which matches Postgres RETURNING Keyword

src/main/java/io/r2dbc/postgresql/codec/NumericDecodeUtils.java, src/test/java/io/r2dbc/postgresql/codec/LongCodecUnitTests.java
If returned OID is big enough (2314556683 for example) codec throws NumberFormatException. 
No new public APIs added
According to documentation (https://www.postgresql.org/docs/12/datatype-oid.html) OID type is "an unsigned four-byte integer", so it is incorrect to decode it as java Integer (which is signed an so has lower max value). 
This pull request decodes OIDs as Long to fix the problem
=> Fix postgres OID type decoding

src/test/java/io/r2dbc/postgresql/AbstractCodecIntegrationTests.java
=> Integration test fails on JDK > 8 because of Instant resolution change

pom.xml
* The CVE is probably not related to how Netty is used in r2dbc-postgresql but nice to use latest patch to avoid warnings from security scanning tools.
=> Bump Netty to 4.1.89.Final, CVE-2022-41915

src/test/java/io/r2dbc/postgresql/AbstractTemporalCodecIntegrationTests.java
Reintroduced JDK > 8 incompatible integration test with java.time.Instant stored as timestamptz.
Instant.now() precision changed from ms to ns after JDK 8, so tests must deal with conversions to postgres μs
=> Adapt integration test to be Java 11 forward-compatible

src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java, src/main/java/io/r2dbc/postgresql/client/SSLSessionHandlerAdapter.java, src/main/java/io/r2dbc/postgresql/client/SSLTunnelHandlerAdapter.java, src/test/java/io/r2dbc/postgresql/client/DowntimeIntegrationTests.java
Refs #595
Handle the inbound connection closing before SSL negotiation and always complete the SSL handshake future.
At first, only added the channel inactive lifecycle event in `SSLSessionHandlerAdapter`. But with the channel pipeline being updated after connect, found that the inbound could already be closed before the handler was added (could check if it's active) but the channel could also be unregistered and outside the event loop and then the handler added event would be pending and never called. So reworked the pipeline changes so that the SSL adapter is added on channel init, so all lifecycle events are received. Pass the handshake Mono via a channel attribute — not sure if there's a better way, and the SSL adapter may already have swapped itself for the underlying SSL handler. …
=> Handle early disconnects before SSL handshake
